# Generated by Django 2.2.4 on 2019-08-08 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Speciality Name')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=models.ForeignKey(help_text='Speciality of doctor.', on_delete=django.db.models.deletion.CASCADE, to='users.Speciality'),
        ),
    ]
