# Generated by Django 2.2.4 on 2019-10-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Registration Number'),
        ),
    ]
