# Generated by Django 2.2.4 on 2019-08-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190808_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='registrationtype',
            options={'verbose_name': 'Tipo de Matrícula', 'verbose_name_plural': 'Tipo de Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
