# Generated by Django 2.2.4 on 2019-08-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190808_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
