# Generated by Django 2.2.4 on 2019-08-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190808_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtype',
            name='slug_name',
            field=models.SlugField(default='registrationtype', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='slug_name',
            field=models.SlugField(default='speciality', max_length=40),
            preserve_default=False,
        ),
    ]
