# Generated by Django 2.2.4 on 2019-08-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='document',
            field=models.SlugField(max_length=10, unique=True, verbose_name='Documento Paciente'),
        ),
    ]
