# Generated by Django 2.2.4 on 2019-08-31 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('weight', models.FloatField(max_length=5, verbose_name='Current patient weight')),
                ('height', models.FloatField(blank=True, max_length=6, null=True, verbose_name='Current patient height')),
                ('type_visit', models.CharField(choices=[('First', 'First'), ('Follow-Up', 'Follow-Up')], max_length=10, verbose_name='Visit Type')),
                ('risk_factor', models.BooleanField(help_text='Risk factor item', verbose_name='Risk factor')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_ride', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
