# Generated by Django 2.2.4 on 2019-09-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='concept',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='Concepto final visita'),
        ),
        migrations.AddField(
            model_name='visit',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado de visita'),
        ),
        migrations.CreateModel(
            name='FollowUpVisitComplementInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('depresion_mayor', models.BooleanField(default=False, help_text='item for visit')),
                ('otros_transtornos', models.BooleanField(default=False, help_text='item for visit')),
                ('hta_no_controlada', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_hipoglucemiantes', models.BooleanField(default=False, help_text='item for visit')),
                ('convulsiones', models.BooleanField(default=False, help_text='item for visit')),
                ('factores_predisponentes', models.BooleanField(default=False, help_text='item for visit')),
                ('anorexia', models.BooleanField(default=False, help_text='item for visit')),
                ('abuso_alcohol', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_actual', models.BooleanField(default=False, help_text='item for visit')),
                ('embarazo', models.BooleanField(default=False, help_text='item for visit')),
                ('glaucoma', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_beta_bloqueantes', models.BooleanField(default=False, help_text='item for visit')),
                ('actividad_fisica', models.CharField(choices=[('no', 'no'), ('uno-dos', '1-2 veces por semana'), ('tres-mas', '3 o mas veces por semana')], max_length=10, verbose_name='Actividad Física')),
                ('dieta_hipocalorica', models.BooleanField(default=False, help_text='item for visit')),
                ('palpitaciones_aumento_fc', models.BooleanField(default=False, help_text='item for visit')),
                ('intolerancia_lactosa', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_levodopa', models.BooleanField(default=False, help_text='item for visit')),
                ('hepatitis_aguda', models.BooleanField(default=False, help_text='item for visit')),
                ('hipertension_arterial', models.BooleanField(default=False, help_text='item for visit')),
                ('disfuncion_renal', models.CharField(choices=[('Leve', ' Disfunción Leve'), ('Moderada', 'Disfunción Moderada'), ('Severa', 'Disfunción Severa'), ('IRC Terminal', 'IRC Terminal')], max_length=50, verbose_name='Disfuncion Renal')),
                ('nauseas', models.BooleanField(default=False, help_text='item for visit')),
                ('constipacion', models.BooleanField(default=False, help_text='item for visit')),
                ('cefalea', models.BooleanField(default=False, help_text='item for visit')),
                ('mareos', models.BooleanField(default=False, help_text='item for visit')),
                ('insomnio', models.BooleanField(default=False, help_text='item for visit')),
                ('boca_seca', models.BooleanField(default=False, help_text='item for visit')),
                ('diarrea', models.BooleanField(default=False, help_text='item for visit')),
                ('vomitos', models.BooleanField(default=False, help_text='item for visit')),
                ('dolor_abdominal', models.BooleanField(default=False, help_text='item for visit')),
                ('otros_eventos', models.BooleanField(default=False, help_text='item for visit')),
                ('incio_tratamiento_actual', models.BooleanField(default=False, help_text='item for visit')),
                ('suspendio', models.BooleanField(default=False, help_text='item for visit')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visits.Visit')),
            ],
            options={
                'verbose_name': 'Complemento Visita Seguimiento',
                'verbose_name_plural': 'Complementos para Visitas de Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='FirstVisitComplementInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('depresion_mayor', models.BooleanField(default=False, help_text='item for visit')),
                ('otros_transtornos', models.BooleanField(default=False, help_text='item for visit')),
                ('hta_no_controlada', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_hipoglucemiantes', models.BooleanField(default=False, help_text='item for visit')),
                ('convulsiones', models.BooleanField(default=False, help_text='item for visit')),
                ('factores_predisponentes', models.BooleanField(default=False, help_text='item for visit')),
                ('anorexia', models.BooleanField(default=False, help_text='item for visit')),
                ('abuso_alcohol', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_actual', models.BooleanField(default=False, help_text='item for visit')),
                ('embarazo', models.BooleanField(default=False, help_text='item for visit')),
                ('glaucoma', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_beta_bloqueantes', models.BooleanField(default=False, help_text='item for visit')),
                ('actividad_fisica', models.CharField(choices=[('no', 'no'), ('uno-dos', '1-2 veces por semana'), ('tres-mas', '3 o mas veces por semana')], max_length=10, verbose_name='Actividad Física')),
                ('dieta_hipocalorica', models.BooleanField(default=False, help_text='item for visit')),
                ('palpitaciones_aumento_fc', models.BooleanField(default=False, help_text='item for visit')),
                ('intolerancia_lactosa', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_levodopa', models.BooleanField(default=False, help_text='item for visit')),
                ('funcion_renal', models.CharField(choices=[('Leve', ' Disfunción Leve'), ('Moderada', 'Disfunción Moderada'), ('Severa', 'Disfunción Severa'), ('IRC Terminal', 'IRC Terminal')], max_length=50, verbose_name='Funcion Renal')),
                ('alergia_naltrexona', models.BooleanField(default=False, help_text='item for visit')),
                ('insuficiencia_hepatica', models.CharField(choices=[('No', 'No'), ('Leve', 'Leve'), ('Moderada', 'Moderada a grave')], max_length=10, verbose_name='Insuficiencia hepatica')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visits.Visit')),
            ],
            options={
                'verbose_name': 'Complemento Primera Visita',
                'verbose_name_plural': 'Complementos para Primeras Visitas',
            },
        ),
    ]
