# Generated by Django 2.2.4 on 2019-08-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstVisitComplementInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('depresion_mayor', models.BooleanField(default=False, help_text='item for visit')),
                ('otros_transtornos', models.BooleanField(default=False, help_text='item for visit')),
                ('hta_no_controlada', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_hipoglucemiantes', models.BooleanField(default=False, help_text='item for visit')),
                ('convulsiones', models.BooleanField(default=False, help_text='item for visit')),
                ('factores_predisponentes', models.BooleanField(default=False, help_text='item for visit')),
                ('anorexia', models.BooleanField(default=False, help_text='item for visit')),
                ('abuso_alcohol', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_actual', models.BooleanField(default=False, help_text='item for visit')),
                ('alergia_naltrexona', models.BooleanField(default=False, help_text='item for visit')),
                ('embarazo', models.BooleanField(default=False, help_text='item for visit')),
                ('insuficiencia_hepatica', models.CharField(choices=[('No', 'No'), ('Leve', 'Leve'), ('Moderada', 'Moderada a grave')], max_length=10, verbose_name='Visit Type')),
                ('glaucoma', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_beta_bloqueantes', models.BooleanField(default=False, help_text='item for visit')),
                ('actividad_fisica', models.CharField(choices=[('uno-dos', '1-2 veces por semana'), ('tres-mas', '3 o mas veces por semana')], max_length=10, verbose_name='Visit Type')),
                ('dieta_hipocalorica', models.BooleanField(default=False, help_text='item for visit')),
                ('funcion_renal', models.BooleanField(default=False, help_text='item for visit')),
                ('papitaciones_aumento_fc', models.BooleanField(default=False, help_text='item for visit')),
                ('tratamiento_levodopa', models.BooleanField(default=False, help_text='item for visit')),
                ('intolerancia_lactosa', models.BooleanField(default=False, help_text='item for visit')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visits.Visit')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
