# Generated by Django 2.2.4 on 2019-09-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20190901_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstvisitcomplementinformation',
            name='funcion_renal',
            field=models.CharField(choices=[('leve', ' Disfunción Leve'), ('moderada', 'Disfunción Moderada'), ('normal', 'Normal'), ('severa', 'Disfunción Severa'), ('irc-terminal', 'IRC Terminal')], max_length=50, verbose_name='Funcion Renal'),
        ),
        migrations.AlterField(
            model_name='firstvisitcomplementinformation',
            name='insuficiencia_hepatica',
            field=models.CharField(choices=[('no', 'No'), ('leve', 'Leve'), ('moderada', 'Moderada a grave')], max_length=10, verbose_name='Insuficiencia hepatica'),
        ),
        migrations.AlterField(
            model_name='followupvisitcomplementinformation',
            name='disfuncion_renal',
            field=models.CharField(choices=[('leve', ' Disfunción Leve'), ('moderada', 'Disfunción Moderada'), ('normal', 'Normal'), ('severa', 'Disfunción Severa'), ('irc-terminal', 'IRC Terminal')], max_length=50, verbose_name='Disfuncion Renal'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='type_visit',
            field=models.CharField(choices=[('first', 'First'), ('follow-up', 'Follow-Up')], max_length=10, verbose_name='Visit Type'),
        ),
    ]
