# Generated by Django 2.2.4 on 2019-09-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20190901_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='percentage_evolution',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Porcentaje de evolución del peso'),
        ),
        migrations.AddField(
            model_name='visit',
            name='result_header',
            field=models.TextField(blank=True, null=True, verbose_name='Encabezado de visita'),
        ),
        migrations.AddField(
            model_name='visit',
            name='treatment_weaks',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Semanas de tratamiento'),
        ),
    ]
