# Generated by Django 2.2.4 on 2019-09-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20190902_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='percentage_evolution',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Porcentaje de evolución del peso'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Resultado de visita'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='result_header',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Encabezado de visita'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='treatment_weaks',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Semanas de tratamiento'),
        ),
    ]
