# Generated by Django 2.2.4 on 2019-09-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20190902_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='percentage_evolution',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Porcentaje de evolución del peso'),
        ),
    ]
