# Generated by Django 2.2.4 on 2019-09-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_auto_20190902_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='percentage_evolution',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Porcentaje de evolución del peso'),
        ),
    ]
