# Generated by Django 2.2.4 on 2019-09-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_auto_20190904_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstvisitcomplementinformation',
            name='cirugia_planificada',
            field=models.BooleanField(default=False, help_text='item for visit'),
        ),
        migrations.AddField(
            model_name='followupvisitcomplementinformation',
            name='cirugia_planificada',
            field=models.BooleanField(default=False, help_text='item for visit'),
        ),
    ]
